name: Push to main
on:
  push:
    branches:
      - 'main'
jobs:
  stuff:
    runs-on: ubuntu-latest
    if: 1 == 0
    steps:
      - run: echo 'stuff'
  things:
    runs-on: ubuntu-latest
    needs: [stuff]
    # if: always() && ${{ needs.stuff.result }} === 'failure' && ${{ needs.stuff.outputs.step-result }} === 'success'
    # if: always()
    steps:
      - run: echo 'things'
