name: Push to main
on:
  push:
    branches:
      - 'main'
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  stuff2:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'stuff'
  
  things:
    runs-on: ubuntu-latest
    needs: [stuff, stuff2]
    # if: always() && (needs.stuff.result == 'success' || needs.stuff2.result == 'success')
    # if: always() && ${{ needs.stuff.result }} === 'failure' && ${{ needs.stuff.outputs.step-result }} === 'success'
    # if: always()
    if: always() && needs.stuff.result == 'failure'
    steps:
      - run: echo 'things'
