name: Run on pull_request
on:
    pull_request:
jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Dump github context
        env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Run GH action from dev branch
        id: sorting-hat
        # Replace v1 with the SODEV branch name when testing
        uses: buildcom/the-sorting-hat@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get output
        env:
            CURRENT_LABELS: ${{ steps.sorting-hat.outputs.labels }}
        run: echo "$CURRENT_LABELS"
