name: On pull_request_review
on:
  pull_request_review:
jobs:
  get-payload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context to file
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" > ${{ github.event_name }}-${{ github.run_id }}-payload.json
      - name: Upload to artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event_name }}-${{ github.run_id }}-payload
          path: ${{ github.event_name }}-${{ github.run_id }}-payload.json
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run GH action from dev branch
        id: sorting-hat
        # Replace v1 with the SODEV branch name when testing
        uses: buildcom/the-sorting-hat@SODEV-33350
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get output
        env:
            CURRENT_LABELS: ${{ steps.sorting-hat.outputs.labels }}
        run: echo "$CURRENT_LABELS"
